pipeline:
  name: scan
  identifier: scan
  projectIdentifier: simplejavamavenappharness
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: AwsEKSGithub
        repoName: simple-java-maven-app
        build: <+input>
  stages:
    - stage:
        name: security
        identifier: security
        description: ""
        type: SecurityTests
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Security
                  name: security
                  identifier: security
                  spec:
                    privileged: true
                    settings:
                      policy_type: orchestratedScan
                      scan_type: repository
                      product_name: aqua-trivy
                      product_config_name: aqua-trivy
                    imagePullPolicy: Always
